### ISSUE TITLE
Bullying

### ISSUE THREAD

**Issue by AdriMariani** [AdamZed/DRAMZ#7]
Vince has been bullying me

**Comment by Vaddante** [comment]
Dante has been bullying me

**Comment by Vaddante** [comment]
Adraino has too

**Comment by Vaddante** [comment]
Adriano has been bullying me. ;~;

**Comment by AdriMariani** [comment]
vindollar hahahahaha

**Comment by GuyFier1** [comment]
Everyone is bullying me :'(

**Comment by ghost** [comment]
Adam is suppressing my freedom of speech

**Comment by ghost** [comment]
#anazi
